language: c

compiler:
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison
 - sudo apt-get install -qq cmocka-doc libcmocka-dev libcmocka0
 - sudo apt-get install -qq valgrind
 
before_script: make

script: make test
