language: c

compiler:
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison
 - sudo apt-get install -qq cmocka-doc libcmocka-dev libcmocka0

before_script: make
script: make test
after_script: make clean
