name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt update
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq flex bison
        sudo apt-get install -qq cmocka-doc libcmocka-dev libcmocka0
        sudo apt-get install -qq valgrind
        sudo apt-get install -qq doxygen
      
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make clean
      run: make clean
